# Generated by Django 5.2.8 on 2026-09-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='subscription_data',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='player_id',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
