# Generated by Codex on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
