services:
  - type: web
    name: starclinch-assignment-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      # Add your other environment variables here securely in the Render Dashboard
